/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2018-03-04 08:07:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AdminPageFunMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body{\r\n");
      out.write("margin:0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul{\r\n");
      out.write("list-style-type:none;\r\n");
      out.write("margin:0;\r\n");
      out.write("padding:0;\r\n");
      out.write("width:100%;\r\n");
      out.write("background-color:#2C3539;\r\n");
      out.write("position:fixed;\r\n");
      out.write("height:100%;\r\n");
      out.write("overflow:auto;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li a{\r\n");
      out.write("display:block;\r\n");
      out.write("color:white;\r\n");
      out.write("padding:20px 30px;\r\n");
      out.write("text-decoration:none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li{\r\n");
      out.write("text-align:center;\r\n");
      out.write("border-bottom:1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("li a:hover{\r\n");
      out.write("background-color:#000000;\r\n");
      out.write("color:#25587E;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style></head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<ul>\r\n");
      out.write("\r\n");
      out.write("\t<li><a class=\"active\" href=\"FunMenuOfOrderM.jsp\" target=\"funOfEachMenu\"><font size=4>Orders</font></a></li>\r\n");
      out.write("\t<li><a href=\"viewCusInfo.jsp\" target=\"bodyOfFun\"><font size=4 >View Customers</font></a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t<li><a href=\"FunMenuOfMenu.jsp \" target=\"funOfEachMenu\"><font size=4>Menu Management</font></a></li>\r\n");
      out.write("\t<li><a href=\"FunMenuOfEmployeeM.jsp\" target=\"funOfEachMenu\"><font size=4>Employee Management</font></a></li>\r\n");
      out.write("\t<li><a href=\"FunMenuOfProfile.jsp\" target=\"funOfEachMenu\"><font size=4>Profile</font></a></li>\r\n");
      out.write("\t<li><a href=\"realIndex.html\" target=\"#k\"><font size=4>Log Out</font></a></li>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</ul>\r\n");
      out.write("</body></html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
