/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2018-03-03 08:44:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;

public final class canEditEmpInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/importfile.jsp", Long.valueOf(1519226520000L));
    _jspx_dependants.put("/dbConnector.jsp", Long.valueOf(1519226598000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"updateEmpInfo.jsp\">\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write(" \r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

Class.forName("com.mysql.jdbc.Driver");
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost/foodordering","root","root");
		Statement st=con.createStatement();
		
		
		 
      out.write('\r');
      out.write('\n');


String emp_name=request.getParameter("EditEmpName");
HttpSession ss=request.getSession(true);
ss.setAttribute("emp_name",emp_name);




String sql="select * from foodordering.employee_info where employee_name='"+emp_name+"'";
ResultSet rs=st.executeQuery(sql);

//String emp_id="";
String emp_phone="";
String emp_email="";
String emp_address="";
String emp_status="";
String working_status="";
if(rs.next()){
	 //emp_id=rs.getString(1);
	 emp_phone=rs.getString(3);
	 emp_email=rs.getString(4);
	 emp_address=rs.getString(5);
	 emp_status=rs.getString(6);
	 working_status=rs.getString(7);
	
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<table align=center cellpadding=16px bgcolor=#d3d3d3>\r\n");
      out.write("\r\n");
      out.write("<tr><td><font size=4>Employee_phone:</font></td><td><input type=\"text\" name=\"emp_ph\" value=\"");
      out.print(emp_phone );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td><font size=4>Employee_email:</font></td><td><input type=\"text\" name=\"emp_email\" value=\"");
      out.print(emp_email );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td><font size=4>Employee_address:</font></td><td><input type=\"text\" name=\"emp_adr\" value=\"");
      out.print(emp_address);
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td><font size=4>Employee_status:</font></td><td><input type=\"text\" name=\"emp_sts\" value=\"");
      out.print(emp_status );
      out.write("\"></td></tr>\r\n");
      out.write("<tr><td><font size=4>Working_status:</font></td><td><input type=\"text\" name=\"wk_sts\" value=\"");
      out.print(working_status );
      out.write("\"></td></tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<tr><td></td><td></td><td><input type=\"submit\" value=\"Update\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
