/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2018-03-05 14:38:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;

public final class customerRegBtnAction1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/importfile.jsp", Long.valueOf(1519226520000L));
    _jspx_dependants.put("/dbConnector.jsp", Long.valueOf(1519226598000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


request.setAttribute("alertMsg2","You must fill in each text Box!");
request.setAttribute("alertMsg3","You have already registered!!");
String message="";
String cus_id="";

System.out.println("K");
String cus_fname=request.getParameter("c_fname");
String cus_lname=request.getParameter("c_lname");
String cus_ph=request.getParameter("c_ph");
String cus_email=request.getParameter("c_emailadr");
String cus_adr=request.getParameter("c_adr");
String cus_pwd=request.getParameter("c_pwd");

HttpSession ss=request.getSession(true);
	
	ss.setAttribute("c_fname",cus_fname);
	ss.setAttribute("c_lname",cus_lname);



      out.write('\r');
      out.write('\n');
 
if(cus_fname==""||cus_lname=="" || cus_ph=="" || cus_email=="" || cus_adr==""){
	
	message =(String)request.getAttribute("alertMsg2");
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t var msg2=\"");
      out.print(message);
      out.write("\";\r\n");
      out.write("\t alert(msg2);\r\n");
      out.write("     \r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

	
	RequestDispatcher rd=request.getRequestDispatcher("customerRegistration.jsp");
	rd.include(request,response);
	
}
else{
try{
	
      out.write('\r');
      out.write('\n');
      out.write('	');
      out.write(" \r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

Class.forName("com.mysql.jdbc.Driver");
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost/foodordering","root","root");
		Statement st=con.createStatement();
		
		
		 
      out.write('\r');
      out.write('\n');
      out.write('	');

	String sqlquery="select * from customer_info where customer_firstname='"+cus_fname+"' and customer_lastname='"+cus_lname+"'";
	System.out.println("database query");
	ResultSet rs=st.executeQuery(sqlquery);
	if(rs.next()){
		message =(String)request.getAttribute("alertMsg3");
		
      out.write("\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t var msg3=\"");
      out.print(message);
      out.write("\";\r\n");
      out.write("\t\t alert(msg3);\r\n");
      out.write("\t     \r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t");

	RequestDispatcher rd=request.getRequestDispatcher("customerRegistration.jsp");
	rd.include(request,response);
		//<redirect to this page>
		
	}
	else{
		
		
		 String insertStr="insert into customer_info(customer_firstname,customer_lastname,customer_phone,customer_email,customer_address,password) values ('"+cus_fname+"','"+cus_lname+"','"+cus_ph+"','"+cus_email+"','"+cus_adr+"','"+cus_pwd+"')";
		 
		    int n=st.executeUpdate(insertStr);
		    if(n==1)
			  {
				// out.println("<font size=5 face='' color='blue'>Successfully Registered!!</font>");
				response.sendRedirect("getCusId.jsp");
			   }
		 
			
		}
}
	
 catch(Exception ex){
 }
}
 
      out.write("\r\n");
      out.write(" </body>\r\n");
      out.write(" </html>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
