/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2018-03-04 13:46:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;
import java.io.*;
import java.util.*;
import javax.servlet.*;
import javax.servlet.http.*;
import java.sql.*;

public final class EmployeeRegAction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/importfile.jsp", Long.valueOf(1519226520000L));
    _jspx_dependants.put("/dbConnector.jsp", Long.valueOf(1519226598000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<body>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

request.setAttribute("alertMsg2","You must fill in each text Box!");
String message="";
String e_id=request.getParameter("e_id");
String e_name=request.getParameter("e_name");

String e_ph=request.getParameter("e_ph");
String e_emailadr=request.getParameter("e_emailadr");
String e_adr=request.getParameter("e_adr");
String e_status=request.getParameter("e_status");
String e_pwd=request.getParameter("e_pwd");

if(e_id==""||e_name=="" || e_ph=="" || e_emailadr==""|| e_status==" " || e_pwd==" "){
	message =(String)request.getAttribute("alertMsg2");
	
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t var msg1=\"");
      out.print(message);
      out.write("\";\r\n");
      out.write("\t alert(msg1);\r\n");
      out.write("     \r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

	RequestDispatcher rd=request.getRequestDispatcher("EmployeeRegistration.jsp");
	rd.include(request,response);
	
}
else{
	try{
		
      out.write("\r\n");
      out.write("\t\t");
      out.write(" \r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

Class.forName("com.mysql.jdbc.Driver");
		Connection con=DriverManager.getConnection("jdbc:mysql://localhost/foodordering","root","root");
		Statement st=con.createStatement();
		
		
		 
      out.write("\r\n");
      out.write("\t\t");

		String sql="select * from foodordering.employee_info where employee_id='"+e_id+"'";
		ResultSet rs=st.executeQuery(sql);
		if(rs.next()){
			response.sendRedirect("EmployeeRegistration.jsp");
		}
		else{
			String insertSql="insert into foodordering.employee_info(employee_id,employee_name,employee_phone,employee_email,employee_address,employee_status,password)values('"+e_id+"','"+e_name+"','"+e_ph+"','"+e_emailadr+"','"+e_adr+"','"+e_status+"','"+e_pwd+"')";
		    int n=st.executeUpdate(insertSql);
		    if(n==1)
			  {
				  out.println("<font size=5 face='' color='blue'>Successfully Registered!!</font>");
			  }
		}
	}
	catch(Exception ex){
		
	}

}

      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
