/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2018-03-04 08:03:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class FunMenuOfMenu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write(".menuBtn1{\r\n");
      out.write("background-color:#d3d3d3;\r\n");
      out.write("height:100%;\r\n");
      out.write("width:150px;\r\n");
      out.write("height:50px;\r\n");
      out.write("}\r\n");
      out.write(".menuBtn1:focus{\r\n");
      out.write("background-color:#25587E;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<table border=0 width=100% height=100%>\r\n");
      out.write("\r\n");
      out.write("<tr><td><a href=\"viewMenu.jsp\" target=\"bodyOfFun\"><button type=\"button\" class=\"menuBtn1\"><font face=\"broadway\" size=3>\r\n");
      out.write("\tViewMenu</font></button></a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td><a href=\"AddNewMenu.jsp\" target=\"bodyOfFun\"><button type=\"button\" class=\"menuBtn1\"><font face=\"broadway\" size=3>\r\n");
      out.write("\tAdd New Menu</font></button></a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td><a href=\"DedicateMenu.jsp\" target=\"bodyOfFun\"><button type=\"button\" class=\"menuBtn1\"><font face=\"broadway\" size=3>\r\n");
      out.write("\tDedicate_Menu</font></button></a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td><a href=\"RestoreMenu.jsp\" target=\"bodyOfFun\"><button type=\"button\" class=\"menuBtn1\"><font  face=\"broadway\" size=3>\r\n");
      out.write("\tRestore Menu</font></button></a></td>\r\n");
      out.write("\t\r\n");
      out.write("\t<td><a href=\"editMenuFramePage.jsp\" target=\"bodyOfFun\"><button type=\"button\" class=\"menuBtn1\"><font face=\"broadway\" size=3>\r\n");
      out.write("\tEdit Menu</font></button></a></td></tr></table>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
